web development/sizeup/administrador/urls.py
from django.conf.urls import url

from views import *

urlpatterns = [
	url(r'^$', Index.as_view(), name="index"),
    url(r'^registrar_avaliavel/$', RegistrarAvaliavel.as_view(), name="registrar_avaliavel"),
    url(r'^pesquisar_avaliavel/$', PesquisarAvaliavel.as_view(), name="pesquisar_avaliavel"),
]

web development/sizeup/sizeup/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sizeup.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^adm/', include('administrador.urls', namespace="adm")),
)

web development/sizeup/administrador/models.py
from django.db import models

# Create your models here.

web development/sizeup/administrador/forms.py
from django import forms

class Form_Avaliavel_Register(forms.Form):
	CHOICE = (
		('2', 'AVALIAVEL'),
		('3', 'VINI PORCA ROSA'),
	)

	email = forms.EmailField()
	telefone = forms.CharField(max_length=50)
	password1 = forms.CharField(max_length=16)
	password2 = forms.CharField(max_length=16)
	nivel = forms.ChoiceField(choices=CHOICE)

	cnpj = forms.CharField(max_length=50)
	razao_social = forms.CharField(max_length=100)
	nome_fantasia = forms.CharField(max_length=100)
	email_institucional = forms.EmailField()

	nome_responsavel = forms.CharField(max_length=100)
	email_responsavel = forms.EmailField()
	cpf_responsavel = forms.CharField(max_length=50)
	telefone_responsavel = forms.CharField(max_length=50)

class Form_Avaliavel_Register_Beta(forms.Form):
	

	SS = (
		('Culinario', 
			(
				('restaurante','restaurante'),('pizzaria','pizzaria'),('lanchonete', 'lanchonete')
			)
		),
	)

	nome = forms.CharField(max_length=50)
	telefone = forms.CharField(max_length=50)
	setor = forms.CharField(max_length=50)
	especialidade = forms.CharField(max_length=50, required=False)

	estado = forms.CharField(max_length=50)
	municipio = forms.CharField(max_length=50)
	bairro = forms.CharField(max_length=50)
	rua = forms.CharField(max_length=50)
	numero = forms.CharField(max_length=50)

class Form_Search_Test(forms.Form):
	nome = forms.CharField(max_length=100)

web development/sizeup/administrador/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import View

# My imports
from forms import *
from avaliavel.models import *
from core.models import *


class Index(View):
	template = "administrador/index.html"
	def get(self, request):
		return render(request, self.template, {})

class RegistrarAvaliavel(View):
	template = "administrador/registro_avaliavel.html"
	form_class = Form_Avaliavel_Register_Beta
	def get(self, request):
		form = self.form_class()
		return render(request, self.template, {'form':form})

	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			estado = form.cleaned_data['estado']
			municipio = form.cleaned_data['municipio']
			bairro = form.cleaned_data['bairro']
			rua = form.cleaned_data['rua']
			numero = form.cleaned_data['numero']
			
			endereco = Endereco_Beta(estado=estado,municipio=municipio,bairro=bairro,rua=rua,numero=numero)
			endereco.save()

			telefone = form.cleaned_data['telefone']
			nome = form.cleaned_data['nome']
			setor = form.cleaned_data['setor']
			especialidade = form.cleaned_data['especialidade']
			avaliavel = Avaliavel_Beta(telefone=telefone,nome=nome,setor=setor,especialidade=especialidade,endereco_beta=endereco)
			avaliavel.save()
		return render(request, self.template, {'form':form})


class PesquisarAvaliavel(View):
	template = "administrador/pesquisar_avaliavel.html"
	form_class = Form_Search_Test

	def get(self, request):
		form = self.form_class()
		return render(request, self.template, {'form':form})	

	def post(self, request):
		avaliaveis = None
		form = self.form_class(request.POST)
		if form.is_valid():
			nome = form.cleaned_data['nome']
			avaliaveis = Avaliavel_Beta.objects.filter(nome__icontains=nome)
		return render(request, self.template, {'avaliaveis':avaliaveis, 'form':form})

web development/sizeup/administrador/templates/administrador/index.html
<a href="{%url 'adm:registrar_avaliavel'%}">Registrar</a><br/>
<a href="{%url 'adm:pesquisar_avaliavel'%}">Pesquisar</a>

web development/sizeup/administrador/templates/administrador/pesquisar_avaliavel.html
<a href="{%url 'adm:registrar_avaliavel'%}">Registrar</a><br/>
{% if form %}
	<form method="POST" action=".">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit", value="Search">
	</form>
{% endif %}

{% if avaliaveis %}
		<table>
			<thead>
				<tr>
					<th>Nome</th>
					<th>Telefone</th>
				</tr>
			</thead>
			<tbody>
				
	{% for av in avaliaveis %}
				<tr>
					<td>{{av.nome}}</td>
					<td>{{av.telefone}}</td>
				</tr>
	{% endfor %}
			</tbody>
		<table>
{% endif %}

web development/sizeup/administrador/templates/administrador/registro_avaliavel.html
<a href="{%url 'adm:pesquisar_avaliavel'%}">Pesquisar</a><br/>
{% if form %}
	
	<form method="post" action=".">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Salvar" />
	</form>

{% endif %}